# Generated by Django 6.0.6 on 2026-07-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Province ecclésiale',
                'verbose_name_plural': 'Provinces ecclésiales',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Région ecclésiale',
                'verbose_name_plural': 'Régions ecclésiales',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='recensement.province')),
            ],
            options={
                'verbose_name': 'District ecclésial',
                'verbose_name_plural': 'Districts ecclésiaux',
                'ordering': ['nom'],
                'unique_together': {('province', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='recensement.region'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='recensement.district')),
            ],
            options={
                'verbose_name': 'Zone ecclésiale',
                'verbose_name_plural': 'Zones ecclésiales',
                'ordering': ['nom'],
                'unique_together': {('district', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='recensement.zone')),
            ],
            options={
                'verbose_name': 'Village / Quartier',
                'verbose_name_plural': 'Villages / Quartiers',
                'ordering': ['nom'],
                'unique_together': {('zone', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='FicheParoisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelle_localite_nom', models.CharField(blank=True, help_text="À remplir uniquement si la localité n'existe pas dans la liste ci-dessus.", max_length=200)),
                ('nom_paroisse', models.CharField(max_length=200)),
                ('annee_fondation', models.PositiveIntegerField(blank=True, null=True)),
                ('parish_shepherd', models.CharField(max_length=200)),
                ('contact_responsable', models.CharField(blank=True, max_length=30)),
                ('nombre_fideles_estime', models.PositiveIntegerField(blank=True, help_text='Estimation du nombre de fidèles.', null=True)),
                ('statut_batiment', models.CharField(choices=[('terrain_nu', 'Terrain nu (pas encore de construction)'), ('en_construction', 'Bâtiment en construction'), ('acheve', 'Bâtiment achevé / en dur'), ('loue', 'Salle ou local loué'), ('prete', 'Salle prêtée / domicile privé'), ('autre', 'Autre')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('precision_gps', models.FloatField(blank=True, help_text='Précision de la capture GPS, en mètres.', null=True)),
                ('nom_agent', models.CharField(max_length=150)),
                ('contact_agent', models.CharField(blank=True, max_length=30)),
                ('observations', models.TextField(blank=True)),
                ('date_recensement', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches', to='recensement.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches', to='recensement.province')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches', to='recensement.region')),
                ('village', models.ForeignKey(blank=True, help_text='Choisir si le village figure déjà dans le référentiel officiel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches', to='recensement.village')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches', to='recensement.zone')),
            ],
            options={
                'verbose_name': 'Fiche de recensement de paroisse',
                'verbose_name_plural': 'Fiches de recensement de paroisses',
                'ordering': ['-date_recensement'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('region', 'nom')},
        ),
    ]
