# Generated by Django 6.0.6 on 2026-07-07 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheparoisse',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text='Compte connecté ayant enregistré cette fiche (rempli automatiquement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super administrateur'), ('manager', 'Manager (chef de province)'), ('superviseur', 'Superviseur (chef de district)'), ('agent', 'Agent recenseur')], default='agent', max_length=20)),
                ('district', models.ForeignKey(blank=True, help_text='Obligatoire si le rôle est Superviseur (définit le district supervisé).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superviseurs', to='recensement.district')),
                ('province', models.ForeignKey(blank=True, help_text='Obligatoire si le rôle est Manager (définit la province supervisée).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='recensement.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
