# Generated by Django 5.0.14 on 2026-07-09 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0004_historiquemodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheparoisse',
            name='contact_informateur',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='nom_informateur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='photo_charge',
            field=models.ImageField(blank=True, help_text='Photo du chargé de paroisse (facultative).', null=True, upload_to='paroisses/charges/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='PhotoParoisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='paroisses/photos/%Y/%m/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='recensement.ficheparoisse')),
            ],
            options={
                'verbose_name': 'Photo de paroisse',
                'verbose_name_plural': 'Photos de paroisse',
                'ordering': ['date_ajout'],
            },
        ),
    ]
