# Generated by Django 5.0.14 on 2026-07-10 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_recensement', models.DateTimeField(help_text='Date à laquelle cette soumission a été recueillie sur le terrain.')),
                ('parish_shepherd', models.CharField(max_length=200)),
                ('contact_responsable', models.CharField(blank=True, max_length=30)),
                ('photo_charge', models.ImageField(blank=True, help_text='Photo du chargé de paroisse (facultative).', null=True, upload_to='census/responsables/%Y/%m/')),
                ('nombre_fideles_estime', models.PositiveIntegerField(blank=True, help_text='Estimation du nombre de fidèles.', null=True)),
                ('nom_informateur', models.CharField(blank=True, max_length=200)),
                ('contact_informateur', models.CharField(blank=True, max_length=30)),
                ('observations', models.TextField(blank=True)),
                ('statut_validation', models.CharField(choices=[('attente_superviseur', 'En attente du chef de district'), ('attente_manager', 'En attente du chef de province'), ('validee', 'Validée')], default='attente_superviseur', max_length=25)),
                ('date_validation_superviseur', models.DateTimeField(blank=True, null=True)),
                ('date_validation_manager', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, help_text='Compte connecté ayant enregistré cette soumission (rempli automatiquement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soumission de recensement',
                'verbose_name_plural': 'Soumissions de recensement',
                'ordering': ['-date_recensement'],
            },
        ),
    ]
