# Generated by Django 5.0.14 on 2026-07-10 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_migrer_fiches_benin'),
        ('parishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubmission',
            name='parish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='parishes.parish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='censussubmission',
            name='valide_par_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions_validees_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='censussubmission',
            name='valide_par_superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions_validees_superviseur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='censussubmission',
            index=models.Index(fields=['parish', 'statut_validation'], name='census_cens_parish__46b53d_idx'),
        ),
    ]
