# Generated by Django 5.0.14 on 2026-07-10 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_migrer_donnees_benin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('annee_fondation', models.PositiveIntegerField(blank=True, null=True)),
                ('statut_batiment', models.CharField(blank=True, choices=[('terrain_nu', 'Terrain nu (pas encore de construction)'), ('en_construction', 'Bâtiment en construction'), ('acheve', 'Bâtiment achevé / en dur'), ('loue', 'Salle ou local loué'), ('prete', 'Salle prêtée / domicile privé'), ('autre', 'Autre')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('precision_gps', models.FloatField(blank=True, help_text='Précision de la capture GPS, en mètres.', null=True)),
                ('unite_geographique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paroisses', to='geography.unitegeographique')),
            ],
            options={
                'verbose_name': 'Paroisse',
                'verbose_name_plural': 'Paroisses',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['unite_geographique'], name='parishes_pa_unite_g_8a1da3_idx')],
            },
        ),
    ]
