# Generated by Django 5.0.14 on 2026-07-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Code ISO 3166-1 alpha-2, ex : BJ pour le Bénin.', max_length=2, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='NiveauGeographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('rang', models.PositiveSmallIntegerField(help_text='0 = racine de la hiérarchie (le niveau le plus large, ex : Région).')),
                ('nom', models.CharField(help_text='Ex : Région, Province, District, Zone, Village.', max_length=50)),
                ('nom_pluriel', models.CharField(blank=True, max_length=50)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='geography.country')),
            ],
            options={
                'verbose_name': 'Niveau géographique',
                'verbose_name_plural': 'Niveaux géographiques',
                'ordering': ['pays', 'rang'],
            },
        ),
        migrations.CreateModel(
            name='UniteGeographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('code_externe', models.CharField(blank=True, help_text="Code optionnel d'un référentiel externe (recensement national, etc.).", max_length=30)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='geography.niveaugeographique')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='geography.unitegeographique')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='geography.country')),
            ],
            options={
                'verbose_name': 'Unité géographique',
                'verbose_name_plural': 'Unités géographiques',
                'ordering': ['pays', 'niveau__rang', 'nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='niveaugeographique',
            constraint=models.UniqueConstraint(fields=('pays', 'rang'), name='niveau_unique_par_pays_et_rang'),
        ),
        migrations.AddIndex(
            model_name='unitegeographique',
            index=models.Index(fields=['pays', 'niveau', 'parent'], name='geography_u_pays_id_f5e31b_idx'),
        ),
    ]
