# Generated by Django 6.0.6 on 2026-07-07 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0002_ficheparoisse_cree_par_profil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheparoisse',
            name='contact_agent',
        ),
        migrations.RemoveField(
            model_name='ficheparoisse',
            name='nom_agent',
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='date_validation_manager',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='date_validation_superviseur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='statut_validation',
            field=models.CharField(choices=[('attente_superviseur', 'En attente du chef de district'), ('attente_manager', 'En attente du chef de province'), ('validee', 'Validée')], default='attente_superviseur', max_length=25),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='valide_par_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='valide_par_superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees_superviseur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ficheparoisse',
            constraint=models.UniqueConstraint(fields=('zone', 'nom_paroisse', 'parish_shepherd'), name='unique_paroisse_zone_nom_charge'),
        ),
    ]
