# Generated by Django 6.0.6 on 2026-07-07 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0003_remove_ficheparoisse_contact_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(help_text='Raison de la modification, fournie par la personne qui modifie.')),
                ('donnees_avant', models.JSONField(help_text='Valeurs des champs juste avant cette modification.')),
                ('donnees_apres', models.JSONField(help_text='Valeurs des champs juste après cette modification.')),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='recensement.ficheparoisse')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques de modification',
                'ordering': ['-date_modification'],
            },
        ),
    ]
