# Generated by Django 5.0.14 on 2026-07-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0005_ficheparoisse_contact_informateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheparoisse',
            name='contact_responsable',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
