# Generated by Django 5.0.14 on 2026-07-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0006_alter_ficheparoisse_contact_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheparoisse',
            name='contact_informateur',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
