# Generated by Django 5.0.14 on 2026-07-16 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0008_refonte_roles_et_rattachements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, help_text='Code court stable pour les identifiants (ex : D01, D02…). Généré automatiquement si laissé vide.', max_length=10),
        ),
        migrations.AlterField(
            model_name='ficheparoisse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ficheparoisse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='ficheparoisse',
            name='precision_gps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Précision GPS'),
        ),
        migrations.AlterField(
            model_name='ficheparoisse',
            name='statut_validation',
            field=models.CharField(choices=[('attente_superviseur', "En attente de l'OP DISTRICT"), ('attente_manager', "En attente de l'OP PROVINCE"), ('validee', 'Validée')], default='attente_superviseur', max_length=25),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(blank=True, help_text='Code court stable pour les identifiants (ex : P01, P02…). Généré automatiquement si laissé vide.', max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, help_text='Code court stable pour les identifiants (ex : R01, R02…). Généré automatiquement si laissé vide.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(blank=True, help_text='Code court stable pour les identifiants (ex : Z001, Z002…). Généré automatiquement si laissé vide.', max_length=10),
        ),
    ]
