# Generated by Django 5.0.14 on 2026-07-16 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0009_alter_district_code_alter_ficheparoisse_latitude_and_more'),
    ]

    operations = [
        # =====================================================================
        # 1. Ajouter champ `code` sur le modèle Village
        # =====================================================================
        migrations.AddField(
            model_name='village',
            name='code',
            field=models.CharField(
                blank=True,
                max_length=10,
                help_text="Code court stable pour composition des codes officiels "
                          "(ex : Q001, Q002…). Généré automatiquement si laissé vide.",
            ),
        ),

        # =====================================================================
        # 2. Ajouter champs de codification sur FicheParoisse
        # =====================================================================
        migrations.AddField(
            model_name='ficheparoisse',
            name='code_officiel',
            field=models.CharField(
                max_length=50,
                unique=True,
                null=True,
                blank=True,
                help_text="Code officiel généré automatiquement après validation complète. "
                          "Format : BJ-AAAA-RR-PP-DD-ZZ-QQ-XXXX",
            ),
        ),

        migrations.AddField(
            model_name='ficheparoisse',
            name='date_generation_code',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text="Date et heure de génération du code officiel.",
            ),
        ),

        migrations.AddField(
            model_name='ficheparoisse',
            name='genere_par',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                to=settings.AUTH_USER_MODEL,
                related_name='fiches_codes_generes',
                help_text="Utilisateur ayant déclenché la génération du code (système ou admin).",
            ),
        ),

        # =====================================================================
        # 3. Créer modèle de traçabilité CodeParoisseHistorique
        # =====================================================================
        migrations.CreateModel(
            name='CodeParoisseHistorique',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('code_attribue', models.CharField(
                    max_length=50,
                    help_text="Code officiel attribué.",
                )),
                ('date_generation', models.DateTimeField(
                    auto_now_add=True,
                    help_text="Date et heure de génération.",
                )),
                ('donnees_composition', models.JSONField(
                    default=dict,
                    help_text="Données utilisées pour composer le code : "
                              "{'pays': 'BJ', 'annee': 1986, 'region_code': 'R01', ...}",
                )),
                ('fiche', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='recensement.ficheparoisse',
                    related_name='historiques_codes',
                    help_text="Fiche concernée.",
                )),
                ('genere_par', models.ForeignKey(
                    on_delete=django.db.models.deletion.SET_NULL,
                    null=True,
                    blank=True,
                    to=settings.AUTH_USER_MODEL,
                    related_name='codes_generes',
                    help_text="Utilisateur/système ayant généré le code.",
                )),
            ],
            options={
                'verbose_name': 'Traçabilité de code paroisse',
                'verbose_name_plural': 'Traçabilités de codes paroisses',
                'ordering': ['-date_generation'],
            },
        ),
    ]
