# Generated by Django 5.0.14 on 2026-07-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0010_codification_paroisse_village_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheparoisse',
            name='code_officiel',
        ),
        migrations.RemoveField(
            model_name='ficheparoisse',
            name='date_generation_code',
        ),
        migrations.RemoveField(
            model_name='ficheparoisse',
            name='genere_par',
        ),
        migrations.RemoveField(
            model_name='village',
            name='code',
        ),
        migrations.DeleteModel(
            name='CodeParoisseHistorique',
        ),
    ]
