# Generated by Django 5.0.14 on 2026-07-16 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0011_remove_ficheparoisse_code_officiel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='code',
            field=models.CharField(blank=True, help_text='Code court stable pour composition des codes officiels (ex : Q001, Q002…). Généré automatiquement si laissé vide.', max_length=10),
        ),
        migrations.CreateModel(
            name='CodeParoisseHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_attribue', models.CharField(help_text='Code officiel attribué.', max_length=50)),
                ('date_generation', models.DateTimeField(auto_now_add=True, help_text='Date et heure de génération.')),
                ('donnees_composition', models.JSONField(default=dict, help_text="Données utilisées pour composer le code : {'pays': 'BJ', 'annee': 1986, 'region_code': 'R01', ...}")),
                ('fiche', models.ForeignKey(help_text='Fiche concernée.', on_delete=django.db.models.deletion.CASCADE, related_name='historiques_codes', to='recensement.ficheparoisse')),
                ('genere_par', models.ForeignKey(blank=True, help_text='Utilisateur/système ayant généré le code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traçabilité de code paroisse',
                'verbose_name_plural': 'Traçabilités de codes paroisses',
                'ordering': ['-date_generation'],
            },
        ),
    ]
