# Generated by Django 5.0.14 on 2026-07-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0013_restore_ficheparoisse_code_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheparoisse',
            name='code_officiel',
        ),
        migrations.RemoveField(
            model_name='ficheparoisse',
            name='date_generation_code',
        ),
        migrations.RemoveField(
            model_name='ficheparoisse',
            name='genere_par',
        ),
    ]
