# Generated by Django 5.0.14 on 2026-07-16 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0014_remove_ficheparoisse_code_officiel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheparoisse',
            name='code_officiel',
            field=models.CharField(blank=True, help_text='Code officiel généré automatiquement après validation complète. Format : BJ-AAAA-RR-PP-DD-ZZ-QQ-XXXX', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='date_generation_code',
            field=models.DateTimeField(blank=True, help_text='Date et heure de génération du code officiel.', null=True),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='genere_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant déclenché la génération du code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_codes_generes', to=settings.AUTH_USER_MODEL),
        ),
    ]
