# Generated by Django 5.0.14 on 2026-07-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0023_contacts_utilisateurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheparoisse',
            name='statut_batiment_autre',
            field=models.CharField(blank=True, help_text='À renseigner uniquement lorsque le statut du bâtiment est défini sur Autre.', max_length=150, verbose_name='Précision du statut du bâtiment'),
        ),
        migrations.AlterField(
            model_name='ficheparoisse',
            name='statut_batiment',
            field=models.CharField(choices=[('terrain_nu', 'Terrain nu (pas encore de construction)'), ('en_construction', 'Bâtiment en construction'), ('acheve', 'Bâtiment achevé / en dur'), ('loue', 'Salle ou local loué'), ('prete', 'Salle prêtée / domicile privé'), ('lacustre', 'Construction sur l’eau / zone lacustre'), ('autre', 'Autre')], max_length=20),
        ),
    ]
