# Generated by Django 5.0.14 on 2026-07-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0024_ficheparoisse_statut_batiment_autre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheparoisse',
            name='code_court',
            field=models.CharField(blank=True, db_index=True, help_text='Matricule court permanent de la paroisse. Exemple : BJ-P7K4M2.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ficheparoisse',
            name='code_officiel',
            field=models.CharField(blank=True, db_index=True, help_text='Code territorial long généré après validation complète. Exemple : BJ020307014P7K4M2.', max_length=50, null=True, unique=True),
        ),
    ]
