# Generated by Django 5.0.14 on 2026-07-29 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0025_ficheparoisse_code_court_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheparoisse',
            name='date_validation_super_admin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation par le super administrateur'),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='valide_par_super_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_validees_super_admin', to=settings.AUTH_USER_MODEL, verbose_name='Validée par le super administrateur'),
        ),
    ]
