# Generated by Django 5.0.14 on 2026-07-31 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0026_ficheparoisse_date_validation_super_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteparticulier',
            name='date_definition_gps',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de définition de la position GPS'),
        ),
        migrations.AddField(
            model_name='siteparticulier',
            name='details_officiels',
            field=models.TextField(blank=True, verbose_name='Détails officiels du site'),
        ),
        migrations.AddField(
            model_name='siteparticulier',
            name='gps_defini_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_sites_particuliers_definies', to=settings.AUTH_USER_MODEL, verbose_name='Position GPS définie par'),
        ),
        migrations.AddField(
            model_name='siteparticulier',
            name='titre_responsable',
            field=models.CharField(blank=True, help_text='Titre officiel défini par le seed. Le nom de la personne responsable reste séparé.', max_length=200, verbose_name='Titre officiel du responsable'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description officielle du site'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='responsable',
            field=models.CharField(blank=True, help_text="Nom de la personne responsable, complétable si l'information est connue.", max_length=200, verbose_name='Nom du responsable'),
        ),
        migrations.CreateModel(
            name='HistoriqueSiteParticulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification_variable', 'Modification des informations variables'), ('definition_gps', 'Définition initiale du GPS'), ('reinitialisation_gps', 'Réinitialisation du GPS'), ('correction_officielle', 'Correction officielle')], max_length=40)),
                ('motif', models.TextField(blank=True)),
                ('donnees_avant', models.JSONField(blank=True, default=dict)),
                ('donnees_apres', models.JSONField(blank=True, default=dict)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_sites_particuliers', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='recensement.siteparticulier')),
            ],
            options={
                'verbose_name': 'Historique de site particulier',
                'verbose_name_plural': 'Historiques de sites particuliers',
                'ordering': ['-date_action', '-id'],
            },
        ),
    ]
