# Generated by Django 5.0.14 on 2026-07-31 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0027_siteparticulier_date_definition_gps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteparticulier',
            name='date_definition_gps',
        ),
        migrations.RemoveField(
            model_name='siteparticulier',
            name='gps_defini_par',
        ),
        migrations.AlterField(
            model_name='historiquesiteparticulier',
            name='action',
            field=models.CharField(choices=[('creation', 'Création du site'), ('modification_variable', 'Modification des informations variables'), ('definition_gps', 'Définition initiale du GPS'), ('reinitialisation_gps', 'Réinitialisation du GPS'), ('correction_officielle', 'Correction officielle')], max_length=40, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='historiquesiteparticulier',
            name='date_action',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action"),
        ),
        migrations.AlterField(
            model_name='historiquesiteparticulier',
            name='donnees_apres',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données après'),
        ),
        migrations.AlterField(
            model_name='historiquesiteparticulier',
            name='donnees_avant',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données avant'),
        ),
        migrations.AlterField(
            model_name='historiquesiteparticulier',
            name='effectue_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_sites_particuliers', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par'),
        ),
        migrations.AlterField(
            model_name='historiquesiteparticulier',
            name='motif',
            field=models.TextField(blank=True, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='historiquesiteparticulier',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='recensement.siteparticulier', verbose_name='Site particulier'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='details_officiels',
            field=models.TextField(blank=True, help_text='Détails officiels ou description institutionnelle du caractère particulier du site.', verbose_name='Détails officiels du site'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsable de référence'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='titre_responsable',
            field=models.CharField(blank=True, help_text='Titre officiel connu du responsable du site, renseigné par le seed ou à la création.', max_length=200, verbose_name='Titre officiel du responsable'),
        ),
        migrations.CreateModel(
            name='HistoriqueCreationUtilisateurEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_utilise', models.EmailField(blank=True, max_length=254, verbose_name='Adresse e-mail utilisée')),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('non_envoye', 'Non envoyé'), ('echec', 'Échec')], db_index=True, max_length=20)),
                ('motif', models.TextField(blank=True, help_text="Motif d'absence d'envoi ou message d'erreur technique.")),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_creation_utilisateurs_declenches', to=settings.AUTH_USER_MODEL, verbose_name='Compte créé par')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_email_creation', to=settings.AUTH_USER_MODEL, verbose_name='Compte créé')),
            ],
            options={
                'verbose_name': "Historique d'e-mail de création de compte",
                'verbose_name_plural': "Historiques d'e-mails de création de compte",
                'ordering': ['-date_action', '-id'],
                'indexes': [models.Index(fields=['statut', 'date_action'], name='email_creation_statut_date_idx')],
            },
        ),
    ]
