# Generated by Django 5.0.14 on 2026-08-04 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0028_remove_siteparticulier_date_definition_gps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteparticulier',
            name='date_definition_gps',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteparticulier',
            name='gps_defini_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions_gps_sites_particuliers_definies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteparticulier',
            name='zone_rattachement',
            field=models.ForeignKey(help_text='Zone relevant exclusivement du district ecclésial des Sites particuliers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites_particuliers', to='recensement.zone', verbose_name='Zone de rattachement'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='titre_responsable',
            field=models.CharField(blank=True, help_text="Titre local propre au site, s'il existe. Ce champ ne remplace pas le titre du responsable du district.", max_length=200, verbose_name='Titre propre au responsable du site'),
        ),
        migrations.CreateModel(
            name='ResponsabiliteHierarchique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(editable=False, max_length=80, unique=True)),
                ('niveau', models.CharField(choices=[('region', 'Région ecclésiale'), ('province', 'Province ecclésiale'), ('district', 'District ecclésial')], max_length=20)),
                ('titre_officiel', models.CharField(max_length=255)),
                ('nom_responsable', models.CharField(blank=True, help_text="Peut rester vide tant que la personne n'est pas désignée.", max_length=200, verbose_name='Nom du responsable')),
                ('observations', models.TextField(blank=True)),
                ('titre_verrouille', models.BooleanField(default=True)),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites_hierarchiques', to='recensement.district')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsabilites_hierarchiques_modifiees', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites_hierarchiques', to='recensement.province')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsabilites_hierarchiques', to='recensement.region')),
            ],
            options={
                'verbose_name': 'Responsabilité hiérarchique',
                'verbose_name_plural': 'Responsabilités hiérarchiques',
                'ordering': ['niveau', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueResponsabiliteHierarchique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('mise_a_jour_responsable', 'Mise à jour du responsable'), ('correction_reference', 'Correction officielle')], max_length=40)),
                ('motif', models.TextField(blank=True)),
                ('donnees_avant', models.JSONField(blank=True, default=dict)),
                ('donnees_apres', models.JSONField(blank=True, default=dict)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_responsabilites_hierarchiques', to=settings.AUTH_USER_MODEL)),
                ('responsabilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='recensement.responsabilitehierarchique')),
            ],
            options={
                'verbose_name': 'Historique de responsabilité hiérarchique',
                'verbose_name_plural': 'Historiques des responsabilités hiérarchiques',
                'ordering': ['-date_action', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='responsabilitehierarchique',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('district__isnull', True), ('niveau', 'region'), ('province__isnull', True), ('region__isnull', False)), models.Q(('district__isnull', True), ('niveau', 'province'), ('province__isnull', False), ('region__isnull', True)), models.Q(('district__isnull', False), ('niveau', 'district'), ('province__isnull', True), ('region__isnull', True)), _connector='OR'), name='responsabilite_cible_coherente'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitehierarchique',
            constraint=models.UniqueConstraint(condition=models.Q(('niveau', 'region'), ('region__isnull', False)), fields=('region',), name='unique_responsabilite_par_region'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitehierarchique',
            constraint=models.UniqueConstraint(condition=models.Q(('niveau', 'province'), ('province__isnull', False)), fields=('province',), name='unique_responsabilite_par_province'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitehierarchique',
            constraint=models.UniqueConstraint(condition=models.Q(('district__isnull', False), ('niveau', 'district')), fields=('district',), name='unique_responsabilite_par_district'),
        ),
    ]
