# Generated by Django 5.0.14 on 2026-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0029_siteparticulier_date_definition_gps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsabilitehierarchique',
            options={'ordering': ['ordre', 'code'], 'verbose_name': 'Responsabilité hiérarchique des sites particuliers', 'verbose_name_plural': 'Responsabilités hiérarchiques des sites particuliers'},
        ),
        migrations.RemoveConstraint(
            model_name='responsabilitehierarchique',
            name='responsabilite_cible_coherente',
        ),
        migrations.RemoveConstraint(
            model_name='responsabilitehierarchique',
            name='unique_responsabilite_par_region',
        ),
        migrations.RemoveConstraint(
            model_name='responsabilitehierarchique',
            name='unique_responsabilite_par_province',
        ),
        migrations.RemoveConstraint(
            model_name='responsabilitehierarchique',
            name='unique_responsabilite_par_district',
        ),
        migrations.RemoveField(
            model_name='responsabilitehierarchique',
            name='district',
        ),
        migrations.RemoveField(
            model_name='responsabilitehierarchique',
            name='province',
        ),
        migrations.RemoveField(
            model_name='responsabilitehierarchique',
            name='region',
        ),
        migrations.RemoveField(
            model_name='siteparticulier',
            name='zone_rattachement',
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='parent_code',
            field=models.SlugField(blank=True, help_text='Code de la structure parente dans ce référentiel autonome.', max_length=80),
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='structure_nom',
            field=models.CharField(default='', max_length=200, verbose_name='Structure ecclésiale'),
        ),
        migrations.AlterField(
            model_name='district',
            name='est_sites_particuliers',
            field=models.BooleanField(default=False, editable=False, help_text='Champ de compatibilité et de sécurité. Aucun district des Sites particuliers ne doit rester dans le référentiel de recensement.'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='details_officiels',
            field=models.TextField(blank=True, verbose_name='Détails officiels du site'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='titre_responsable',
            field=models.CharField(blank=True, help_text="Titre local propre au site, s'il existe.", max_length=200, verbose_name='Titre propre au responsable du site'),
        ),
    ]
