# Generated by Django 5.0.14 on 2026-08-04 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0030_alter_responsabilitehierarchique_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatResponsableEcclesial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_responsable', models.CharField(blank=True, max_length=200)),
                ('contact_responsable', models.CharField(blank=True, max_length=50)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a_renseigner', 'À renseigner'), ('vacant', 'Vacant'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('termine', 'Terminé'), ('remplace', 'Remplacé')], db_index=True, default='a_renseigner', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('motif_cloture', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mandat de responsable ecclésial',
                'verbose_name_plural': 'Mandats de responsables ecclésiaux',
                'ordering': ['-date_debut', '-date_creation', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='historiqueresponsabilitehierarchique',
            options={'ordering': ['-date_action', '-id'], 'verbose_name': 'Historique de responsabilité ecclésiale', 'verbose_name_plural': 'Historiques des responsabilités ecclésiales'},
        ),
        migrations.AlterModelOptions(
            name='responsabilitehierarchique',
            options={'ordering': ['niveau', 'ordre', 'titre_officiel', 'code'], 'verbose_name': 'Poste ecclésial', 'verbose_name_plural': 'Postes ecclésiaux'},
        ),
        migrations.RemoveField(
            model_name='responsabilitehierarchique',
            name='est_active',
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_ecclesiaux_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postes_ecclesiaux', to='recensement.district'),
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='est_actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postes_ecclesiaux', to='recensement.province'),
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postes_ecclesiaux', to='recensement.region'),
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='site_particulier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postes_ecclesiaux', to='recensement.siteparticulier'),
        ),
        migrations.AddField(
            model_name='responsabilitehierarchique',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postes_ecclesiaux', to='recensement.zone'),
        ),
        migrations.AlterField(
            model_name='historiqueresponsabilitehierarchique',
            name='action',
            field=models.CharField(choices=[('mise_a_jour_responsable', 'Ancienne mise à jour du responsable'), ('creation_poste', 'Création du poste'), ('modification_poste', 'Modification du poste'), ('ouverture_mandat', 'Ouverture du mandat'), ('modification_mandat', 'Modification du mandat'), ('cloture_mandat', 'Clôture du mandat'), ('remplacement', 'Remplacement du responsable'), ('migration_legacy', "Migration d'une ancienne responsabilité"), ('correction_reference', 'Correction officielle')], max_length=40),
        ),
        migrations.AlterField(
            model_name='historiqueresponsabilitehierarchique',
            name='responsabilite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique', to='recensement.responsabilitehierarchique'),
        ),
        migrations.AlterField(
            model_name='responsabilitehierarchique',
            name='code',
            field=models.SlugField(editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='responsabilitehierarchique',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_ecclesiaux_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsabilitehierarchique',
            name='niveau',
            field=models.CharField(choices=[('region', 'Région ecclésiale'), ('province', 'Province ecclésiale'), ('district', 'District ecclésial'), ('zone', 'Zone ecclésiale'), ('site_particulier', 'Site particulier'), ('structure_speciale', 'Structure ecclésiale spéciale')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='responsabilitehierarchique',
            name='nom_responsable',
            field=models.CharField(blank=True, editable=False, help_text='Champ historique à migrer vers les mandats.', max_length=200),
        ),
        migrations.AlterField(
            model_name='responsabilitehierarchique',
            name='observations',
            field=models.TextField(blank=True, editable=False, help_text='Champ historique à migrer vers les mandats.'),
        ),
        migrations.AlterField(
            model_name='responsabilitehierarchique',
            name='parent_code',
            field=models.SlugField(blank=True, help_text="Code facultatif d'un poste ou d'une structure parente autonome.", max_length=120),
        ),
        migrations.AlterField(
            model_name='responsabilitehierarchique',
            name='structure_nom',
            field=models.CharField(blank=True, max_length=255, verbose_name='Structure ecclésiale spéciale ou libellé historique'),
        ),
        migrations.AlterField(
            model_name='responsabilitehierarchique',
            name='titre_verrouille',
            field=models.BooleanField(default=False, help_text="Empêche la modification ordinaire d'un titre officiel seedé."),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='contact_responsable',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Ancien contact du responsable (compatibilité)'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='responsable',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Ancien responsable (compatibilité)'),
        ),
        migrations.AlterField(
            model_name='siteparticulier',
            name='titre_responsable',
            field=models.CharField(blank=True, editable=False, help_text='Champ historique migré vers les postes ecclésiaux.', max_length=200, verbose_name='Ancien titre du responsable (compatibilité)'),
        ),
        migrations.AddIndex(
            model_name='responsabilitehierarchique',
            index=models.Index(fields=['niveau', 'est_actif'], name='poste_niveau_actif_idx'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitehierarchique',
            constraint=models.UniqueConstraint(condition=models.Q(('region__isnull', False)), fields=('region', 'titre_officiel'), name='unique_poste_titre_region'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitehierarchique',
            constraint=models.UniqueConstraint(condition=models.Q(('province__isnull', False)), fields=('province', 'titre_officiel'), name='unique_poste_titre_province'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitehierarchique',
            constraint=models.UniqueConstraint(condition=models.Q(('district__isnull', False)), fields=('district', 'titre_officiel'), name='unique_poste_titre_district'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitehierarchique',
            constraint=models.UniqueConstraint(condition=models.Q(('zone__isnull', False)), fields=('zone', 'titre_officiel'), name='unique_poste_titre_zone'),
        ),
        migrations.AddConstraint(
            model_name='responsabilitehierarchique',
            constraint=models.UniqueConstraint(condition=models.Q(('site_particulier__isnull', False)), fields=('site_particulier', 'titre_officiel'), name='unique_poste_titre_site_particulier'),
        ),
        migrations.AddField(
            model_name='mandatresponsableecclesial',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandats_ecclesiaux_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mandatresponsableecclesial',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandats_ecclesiaux_modifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mandatresponsableecclesial',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandats', to='recensement.responsabilitehierarchique'),
        ),
        migrations.AddField(
            model_name='historiqueresponsabilitehierarchique',
            name='mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='recensement.mandatresponsableecclesial'),
        ),
        migrations.AddIndex(
            model_name='mandatresponsableecclesial',
            index=models.Index(fields=['poste', 'statut'], name='mandat_poste_statut_idx'),
        ),
        migrations.AddConstraint(
            model_name='mandatresponsableecclesial',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['a_renseigner', 'vacant', 'actif', 'suspendu'])), fields=('poste',), name='unique_mandat_courant_par_poste'),
        ),
    ]
