# Generated by Django 5.0.14 on 2026-08-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0031_mandatresponsableecclesial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='affectationterritoriale',
            name='affectation_territoriale_niveau_coherent',
        ),
        migrations.AddField(
            model_name='affectationterritoriale',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_territoriales', to='recensement.province'),
        ),
        migrations.AlterField(
            model_name='affectationterritoriale',
            name='niveau',
            field=models.CharField(choices=[('province', 'Province'), ('district', 'District'), ('zone', 'Zone')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='affectationterritoriale',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('district__isnull', True), ('niveau', 'province'), ('province__isnull', False), ('zone__isnull', True)), models.Q(('district__isnull', False), ('niveau', 'district'), ('province__isnull', True), ('zone__isnull', True)), models.Q(('district__isnull', True), ('niveau', 'zone'), ('province__isnull', True), ('zone__isnull', False)), _connector='OR'), name='affectation_territoriale_niveau_coherent'),
        ),
        migrations.AddConstraint(
            model_name='affectationterritoriale',
            constraint=models.UniqueConstraint(condition=models.Q(('niveau', 'province'), ('province__isnull', False), ('statut', 'active')), fields=('utilisateur', 'province'), name='unique_affectation_active_utilisateur_province'),
        ),
    ]
