# Generated by Django 5.0.14 on 2026-08-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0032_remove_affectationterritoriale_affectation_territoriale_niveau_coherent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteparticulier',
            name='type_site',
            field=models.CharField(choices=[('cathedrale', 'Cathédrale'), ('site_nativite', 'Site de la Nativité'), ('paroisse_mere', 'Paroisse Mère'), ('site_pelerinage', 'Site de Pèlerinage'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Type de site'),
        ),
    ]
