# Generated by Django 5.0.14 on 2026-08-19 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0033_alter_siteparticulier_type_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeEcclesial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Code technique stable utilisé par les seeds et les exports.', max_length=80, unique=True)),
                ('libelle', models.CharField(max_length=180, unique=True)),
                ('abreviation', models.CharField(blank=True, help_text='Exemple : Vn/Sp/Ev.', max_length=40, verbose_name='Abréviation')),
                ('ordre', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('est_actif', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Grade ecclésial',
                'verbose_name_plural': 'Grades ecclésiaux',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='charge_nom',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nom du chargé de paroisse'),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='charge_prenoms',
            field=models.CharField(blank=True, max_length=180, verbose_name='Prénoms du chargé de paroisse'),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='informateur_nom',
            field=models.CharField(blank=True, max_length=120, verbose_name="Nom de l'informateur"),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='informateur_prenoms',
            field=models.CharField(blank=True, max_length=180, verbose_name="Prénoms de l'informateur"),
        ),
        migrations.AddField(
            model_name='mandatresponsableecclesial',
            name='nom',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nom du responsable'),
        ),
        migrations.AddField(
            model_name='mandatresponsableecclesial',
            name='prenoms',
            field=models.CharField(blank=True, max_length=180, verbose_name='Prénoms du responsable'),
        ),
        migrations.AlterField(
            model_name='ficheparoisse',
            name='nom_informateur',
            field=models.CharField(blank=True, help_text='Champ historique conservé pour compatibilité. Il est synchronisé depuis nom/prénoms.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ficheparoisse',
            name='parish_shepherd',
            field=models.CharField(help_text='Champ historique conservé pour compatibilité. Il est synchronisé depuis nom/prénoms.', max_length=200),
        ),
        migrations.AlterField(
            model_name='mandatresponsableecclesial',
            name='nom_responsable',
            field=models.CharField(blank=True, help_text='Champ historique conservé pour compatibilité. Il est synchronisé depuis nom/prénoms.', max_length=200),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='charge_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_charge_paroisse', to='recensement.gradeecclesial', verbose_name='Grade du chargé de paroisse'),
        ),
        migrations.AddField(
            model_name='ficheparoisse',
            name='informateur_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_informateur', to='recensement.gradeecclesial', verbose_name="Grade de l'informateur"),
        ),
        migrations.AddField(
            model_name='mandatresponsableecclesial',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandats_responsables_ecclesiaux', to='recensement.gradeecclesial', verbose_name='Grade du responsable'),
        ),
        migrations.AddIndex(
            model_name='mandatresponsableecclesial',
            index=models.Index(fields=['nom', 'prenoms'], name='mandat_nom_prenoms_idx'),
        ),
    ]
