# Generated by Django 5.0.14 on 2026-08-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0035_gradeecclesial_referentiel_extensible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeecclesial',
            name='abreviation',
            field=models.CharField(blank=True, help_text="Abréviation officielle lorsqu'elle est connue. Ne pas inventer de valeur définitive.", max_length=40, verbose_name='Abréviation'),
        ),
    ]
