# Generated by Django 5.0.14 on 2026-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensement', '0036_alter_gradeecclesial_abreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeecclesial',
            name='categorie',
            field=models.CharField(choices=[('general', 'Corprs de leaders'), ('visionnaire', 'Corps des visionnaires'), ('allagba', 'Corps des Allagba'), ('autre', 'Autre')], db_index=True, default='autre', max_length=20),
        ),
    ]
