# Generated by ChatGPT on 2026-08-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recensement", "0041_seed_roles_plateforme"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieBadgeAdministratif",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("nom", models.CharField(max_length=150, unique=True)),
                ("type_principal", models.CharField(choices=[("mondial", "Mondial"), ("diocesain", "Diocésain"), ("particulier", "Particulier"), ("autre", "Autre catégorie approuvée")], db_index=True, default="autre", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("est_active", models.BooleanField(db_index=True, default=True)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catégorie de badge administratif",
                "verbose_name_plural": "Catégories de badges administratifs",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="BadgeAdministratif",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_badge", models.CharField(db_index=True, editable=False, help_text="Numéro unique du badge, non réattribuable.", max_length=60, unique=True)),
                ("token_public", models.SlugField(db_index=True, editable=False, help_text="Identifiant public non sensible utilisé par le QR code.", max_length=80, unique=True)),
                ("precision_categorie", models.CharField(blank=True, help_text="Exemples : CST, CSMo, Conseil Pastoral, Commission, Mission temporaire.", max_length=180, verbose_name="Précision / sous-catégorie")),
                ("fonction_badge", models.CharField(blank=True, max_length=200, verbose_name="Fonction imprimée sur le badge")),
                ("structure_badge", models.CharField(blank=True, max_length=200, verbose_name="Structure affichée sur le badge")),
                ("diocese", models.CharField(blank=True, max_length=180, verbose_name="Diocèse")),
                ("structure_diocesaine", models.CharField(blank=True, max_length=200, verbose_name="Structure diocésaine")),
                ("niveau_habilitation", models.CharField(blank=True, max_length=150, verbose_name="Niveau d'habilitation")),
                ("date_delivrance", models.DateField(verbose_name="Date de délivrance")),
                ("date_expiration", models.DateField(verbose_name="Date d'expiration")),
                ("statut", models.CharField(choices=[("preparation", "En préparation"), ("actif", "Actif"), ("suspendu", "Suspendu"), ("expire", "Expiré"), ("perdu", "Perdu"), ("vole", "Volé"), ("annule", "Annulé"), ("restitue", "Restitué")], db_index=True, default="preparation", max_length=20)),
                ("publication_photo_autorisee", models.BooleanField(default=False, verbose_name="Autoriser la photo sur la page publique QR")),
                ("mentions_securite", models.TextField(blank=True, verbose_name="Mentions administratives ou de sécurité")),
                ("date_remise", models.DateField(blank=True, null=True, verbose_name="Date de remise")),
                ("date_restitution", models.DateField(blank=True, null=True, verbose_name="Date de restitution")),
                ("etat_restitution", models.CharField(blank=True, choices=[("bon", "Bon état"), ("use", "Usé"), ("deteriore", "Détérioré"), ("non_restitue", "Non restitué")], max_length=20, verbose_name="État du badge à la restitution")),
                ("motif_restitution", models.TextField(blank=True)),
                ("date_desactivation_electronique", models.DateTimeField(blank=True, null=True)),
                ("observations_internes", models.TextField(blank=True, verbose_name="Observations internes")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("badge_remplace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="badges_remplacement", to="recensement.badgeadministratif", verbose_name="Badge remplacé")),
                ("categorie", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="badges", to="recensement.categoriebadgeadministratif", verbose_name="Catégorie du badge")),
                ("cree_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="badges_administratifs_crees", to=settings.AUTH_USER_MODEL)),
                ("employe", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="badges_administratifs", to="recensement.employe")),
                ("modifie_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="badges_administratifs_modifies", to=settings.AUTH_USER_MODEL)),
                ("remis_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="badges_remis", to=settings.AUTH_USER_MODEL)),
                ("restitue_a", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="badges_restitues_receptionnes", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Badge administratif",
                "verbose_name_plural": "Badges administratifs",
                "ordering": ["-date_delivrance", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueBadgeAdministratif",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("creation", "Création du badge"), ("modification", "Modification du badge"), ("remise", "Remise du badge"), ("restitution", "Restitution du badge"), ("activation", "Activation du badge"), ("suspension", "Suspension du badge"), ("annulation", "Annulation du badge"), ("perte", "Déclaration de perte"), ("vol", "Déclaration de vol"), ("expiration", "Expiration constatée"), ("desactivation_electronique", "Désactivation électronique"), ("renouvellement", "Renouvellement"), ("remplacement", "Remplacement"), ("qrcode", "Consultation ou génération QR code"), ("modification_categorie", "Modification de catégorie")], db_index=True, max_length=40)),
                ("ancien_statut", models.CharField(blank=True, max_length=20)),
                ("nouveau_statut", models.CharField(blank=True, max_length=20)),
                ("donnees_avant", models.JSONField(blank=True, default=dict)),
                ("donnees_apres", models.JSONField(blank=True, default=dict)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("motif", models.TextField(blank=True)),
                ("date_action", models.DateTimeField(auto_now_add=True)),
                ("badge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historique", to="recensement.badgeadministratif")),
                ("effectue_par", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="historiques_badges_effectues", to=settings.AUTH_USER_MODEL)),
                ("employe", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="historique_badges", to="recensement.employe")),
            ],
            options={
                "verbose_name": "Historique de badge administratif",
                "verbose_name_plural": "Historiques de badges administratifs",
                "ordering": ["-date_action", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="categoriebadgeadministratif",
            index=models.Index(fields=["type_principal", "est_active"], name="catbadge_type_actif_idx"),
        ),
        migrations.AddIndex(
            model_name="badgeadministratif",
            index=models.Index(fields=["statut", "date_expiration"], name="badge_statut_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="badgeadministratif",
            index=models.Index(fields=["employe", "statut"], name="badge_employe_statut_idx"),
        ),
        migrations.AddIndex(
            model_name="badgeadministratif",
            index=models.Index(fields=["categorie", "statut"], name="badge_categorie_statut_idx"),
        ),
        migrations.AddIndex(
            model_name="historiquebadgeadministratif",
            index=models.Index(fields=["action", "date_action"], name="hist_badge_action_date_idx"),
        ),
        migrations.AddIndex(
            model_name="historiquebadgeadministratif",
            index=models.Index(fields=["badge", "date_action"], name="hist_badge_badge_date_idx"),
        ),
    ]
