# Generated by ChatGPT on 2026-08-24

from django.db import migrations


CATEGORIES = [
    ("mondial", "Mondial", "mondial", "Badge relevant directement d'une institution ou structure mondiale de l'Église.", 10),
    ("diocesain", "Diocésain", "diocesain", "Badge rattaché à une structure diocésaine, avec identification du diocèse.", 20),
    ("particulier", "Particulier", "particulier", "Badge spécifique : CST, CSMo, commission, mission, événement, personnel administratif ou intervenant autorisé.", 30),
    ("mission-temporaire", "Mission temporaire", "particulier", "Badge particulier destiné à une mission administrative limitée dans le temps.", 40),
    ("commission", "Commission", "particulier", "Badge particulier lié à une commission reconnue.", 50),
    ("evenement-institutionnel", "Événement institutionnel", "particulier", "Badge particulier lié à un événement institutionnel autorisé.", 60),
    ("prestataire-autorise", "Prestataire / intervenant autorisé", "particulier", "Badge particulier pour un prestataire ou intervenant autorisé.", 70),
    ("autre", "Autre catégorie approuvée", "autre", "Catégorie complémentaire à utiliser uniquement sur validation administrative.", 90),
]


def seed_categories(apps, schema_editor):
    Categorie = apps.get_model("recensement", "CategorieBadgeAdministratif")
    for code, nom, type_principal, description, ordre in CATEGORIES:
        Categorie.objects.update_or_create(
            code=code,
            defaults={
                "nom": nom,
                "type_principal": type_principal,
                "description": description,
                "ordre": ordre,
                "est_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    # Idempotent : on ne supprime pas les catégories, car des badges peuvent les référencer.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("recensement", "0042_badges_administratifs"),
    ]

    operations = [
        migrations.RunPython(seed_categories, noop_reverse),
    ]
