# Generated by ChatGPT on 2026-08-24

from django.db import migrations


def seed_role_badges(apps, schema_editor):
    RolePlateforme = apps.get_model("recensement", "RolePlateforme")
    PermissionRolePlateforme = apps.get_model("recensement", "PermissionRolePlateforme")

    role, _ = RolePlateforme.objects.update_or_create(
        code="gestionnaire-badges-administratifs",
        defaults={
            "nom": "Gestionnaire Badges administratifs",
            "description": "Gère le registre des badges administratifs, les QR codes, remises, restitutions, suspensions, pertes, vols et renouvellements.",
            "est_actif": True,
        },
    )
    PermissionRolePlateforme.objects.update_or_create(
        role=role,
        module_slug="administration",
        submodule_slug="badges-administratifs",
        defaults={
            "peut_consulter": True,
            "peut_creer": True,
            "peut_modifier": True,
            "peut_archiver": True,
            "peut_administrer": True,
            "peut_gerer_qrcode": True,
            "peut_gerer_acces": True,
        },
    )
    PermissionRolePlateforme.objects.update_or_create(
        role=role,
        module_slug="administration",
        submodule_slug="employes",
        defaults={
            "peut_consulter": True,
            "peut_modifier": True,
            "peut_gerer_qrcode": True,
        },
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("recensement", "0043_seed_categories_badges_administratifs")]
    operations = [migrations.RunPython(seed_role_badges, noop)]
